// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-hero/RedesignedSearch.tsx": () => import("../components/mockups/homepage-hero/RedesignedSearch.tsx")
};
